"use client";

import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { formatCurrencyLkr, formatCurrencyUsd, formatDate, formatNumber, formatPercentage } from "@/lib/formatters";

type Detail = Record<string, unknown> & { id: string; importNo: string; importDate: string; status: "DRAFT" | "CONFIRMED" | "CANCELLED" | "REVERSED"; supplierName: string | null; referenceNo: string | null; containerNo: string | null; notes: string | null; totalKg: number; totalBags: number; totalAmountPaidUsd: number; totalShipmentCostLkr: number; totalExpectedRevenueLkr: number; totalExpectedProfitLkr: number; expectedProfitMarginPercentage: number; items: Array<Record<string, unknown> & { id: string; product: { productName: string; sku: string | null }; quantityKg: number; quantityBags: number; costPerKgLkr: number; costPerBagLkr: number; expectedProfitLkr: number; stockBatch: { batchNo: string; remainingKg: number } | null }>; stockBatches: Array<Record<string, unknown> & { id: string; batchNo: string; initialKg: number; remainingKg: number; remainingBags: number; costPerKgLkr: number; status: string }>; stockMovements: Array<Record<string, unknown> & { id: string; movementType: string; quantityKg: number; reason: string | null; createdAt: string }> };

export default function ImportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [data, setData] = useState<Detail | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await fetch(`/api/imports/${id}`); const result = await response.json(); if (!response.ok) throw new Error(result.message); setData(result.data); } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to load import."); } }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function action(kind: "confirm" | "cancel" | "reverse") { const reason = kind === "reverse" ? window.prompt("Reverse reason") : undefined; if (kind === "reverse" && !reason?.trim()) return; if (!window.confirm(kind === "confirm" ? "Confirming this import will add stock to inventory. This action cannot be freely edited later." : kind === "cancel" ? "Cancel this draft import?" : "Reverse this import and remove unused stock?")) return; const response = await fetch(`/api/imports/${id}${kind === "cancel" ? "" : `/${kind}`}`, { method: kind === "cancel" ? "DELETE" : "POST", headers: { "Content-Type": "application/json" }, body: kind === "reverse" ? JSON.stringify({ reason }) : undefined }); const result = await response.json(); if (!response.ok) { setMessage(result.message); return; } await load(); }
  if (!data) return <main className="p-6 text-neutral-600">{message || "Loading import…"}</main>;
  const totals = [["Total KG", formatNumber(Number(data.totalKg))], ["Total bags", formatNumber(Number(data.totalBags))], ["Amount paid", formatCurrencyUsd(Number(data.totalAmountPaidUsd))], ["Shipment cost", formatCurrencyLkr(Number(data.totalShipmentCostLkr))], ["Expected revenue", formatCurrencyLkr(Number(data.totalExpectedRevenueLkr))], ["Expected profit", formatCurrencyLkr(Number(data.totalExpectedProfitLkr))], ["Margin", formatPercentage(Number(data.expectedProfitMarginPercentage))]];
  return <main className="space-y-6 p-4 text-neutral-900 md:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-neutral-500">Import shipment</p><h1 className="text-3xl font-semibold">{data.importNo}</h1><p className="mt-1 text-sm text-neutral-500">{formatDate(data.importDate)} · {data.supplierName || "No supplier"}</p></div><div className="flex flex-wrap gap-2"><Link href="/import" className="rounded-xl border px-4 py-2 text-sm font-semibold">Back</Link>{data.status === "DRAFT" && <><Link href={`/import/${id}/edit`} className="rounded-xl border px-4 py-2 text-sm font-semibold">Edit Draft</Link><button onClick={() => void action("confirm")} className="rounded-xl bg-[#FFBF01] px-4 py-2 text-sm font-bold">Confirm Import</button><button onClick={() => void action("cancel")} className="rounded-xl bg-red-50 px-4 py-2 text-sm font-semibold text-red-700">Cancel Draft</button></>}{data.status === "CONFIRMED" && <button onClick={() => void action("reverse")} className="rounded-xl bg-orange-50 px-4 py-2 text-sm font-semibold text-orange-800">Reverse Import</button>}</div></div>
    {message && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</div>}
    <section className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-4"><Info label="Status" value={data.status}/><Info label="Reference" value={data.referenceNo || "—"}/><Info label="Container" value={data.containerNo || "—"}/><Info label="Notes" value={data.notes || "—"}/></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{totals.map(([label, value]) => <div key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</section>
    <DataTable title="Import items" heads={["Product", "KG", "Bags", "Cost / KG", "Cost / bag", "Expected profit", "Batch"]}>{data.items.map((item) => <tr key={item.id} className="border-t"><td className="p-4 font-semibold">{item.product.productName}<span className="block text-xs font-normal text-neutral-500">{item.product.sku || "—"}</span></td><td className="p-4">{formatNumber(Number(item.quantityKg))}</td><td className="p-4">{formatNumber(Number(item.quantityBags))}</td><td className="p-4">{formatCurrencyLkr(Number(item.costPerKgLkr))}</td><td className="p-4">{formatCurrencyLkr(Number(item.costPerBagLkr))}</td><td className="p-4">{formatCurrencyLkr(Number(item.expectedProfitLkr))}</td><td className="p-4">{item.stockBatch?.batchNo || "Pending confirmation"}</td></tr>)}</DataTable>
    <DataTable title="Stock batches" heads={["Batch", "Initial KG", "Remaining KG", "Remaining bags", "Cost / KG", "Stock value", "Status"]}>{data.stockBatches.length ? data.stockBatches.map((batch) => <tr key={batch.id} className="border-t"><td className="p-4 font-semibold">{batch.batchNo}</td><td className="p-4">{formatNumber(Number(batch.initialKg))}</td><td className="p-4">{formatNumber(Number(batch.remainingKg))}</td><td className="p-4">{formatNumber(Number(batch.remainingBags))}</td><td className="p-4">{formatCurrencyLkr(Number(batch.costPerKgLkr))}</td><td className="p-4">{formatCurrencyLkr(Number(batch.remainingKg) * Number(batch.costPerKgLkr))}</td><td className="p-4">{batch.status}</td></tr>) : <tr><td colSpan={7} className="p-6 text-center text-neutral-500">No batches created yet.</td></tr>}</DataTable>
    <DataTable title="Movement history" heads={["Type", "Quantity KG", "Reason", "Date"]}>{data.stockMovements.length ? data.stockMovements.map((movement) => <tr key={movement.id} className="border-t"><td className="p-4 font-semibold">{movement.movementType}</td><td className="p-4">{formatNumber(Number(movement.quantityKg))}</td><td className="p-4">{movement.reason || "—"}</td><td className="p-4">{formatDate(movement.createdAt)}</td></tr>) : <tr><td colSpan={4} className="p-6 text-center text-neutral-500">No inventory movements yet.</td></tr>}</DataTable>
  </main>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase text-neutral-500">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function DataTable({ title, heads, children }: { title: string; heads: string[]; children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><h2 className="border-b p-5 text-lg font-semibold">{title}</h2><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-neutral-50"><tr>{heads.map((head) => <th key={head} className="p-4 font-semibold">{head}</th>)}</tr></thead><tbody>{children}</tbody></table></div></section>; }
