"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { formatCurrencyLkr, formatDate, formatNumber, formatPercentage } from "@/lib/formatters";

type ImportRow = {
  id: string; importNo: string; importDate: string; supplierName: string | null;
  status: "DRAFT" | "CONFIRMED" | "CANCELLED" | "REVERSED"; totalKg: number;
  totalBags: number; totalShipmentCostLkr: number; totalExpectedProfitLkr: number;
  expectedProfitMarginPercentage: number; itemCount: number;
};
type Summary = { totalShipmentCostLkr: number; totalKg: number; totalBags: number; totalExpectedRevenueLkr: number; totalExpectedProfitLkr: number; expectedProfitMarginPercentage: number };
const badge: Record<ImportRow["status"], string> = { DRAFT: "bg-neutral-100 text-neutral-700", CONFIRMED: "bg-emerald-100 text-emerald-800", CANCELLED: "bg-red-100 text-red-800", REVERSED: "bg-orange-100 text-orange-800" };

export default function ImportsPage() {
  const [rows, setRows] = useState<ImportRow[]>([]); const [summary, setSummary] = useState<Summary | null>(null);
  const [filters, setFilters] = useState({ q: "", status: "ALL", dateFrom: "", dateTo: "", supplierName: "" }); const [applied, setApplied] = useState(filters);
  const [page, setPage] = useState(1); const [meta, setMeta] = useState({ totalPages: 1, totalCount: 0 }); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setMessage(""); try { const params = new URLSearchParams({ page: String(page), limit: "20" }); Object.entries(applied).forEach(([key, value]) => { if (value && value !== "ALL") params.set(key, value); }); const response = await fetch(`/api/imports?${params}`); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Failed to load imports."); setRows(result.data); setSummary(result.summary); setMeta(result.meta); } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to load imports."); } finally { setLoading(false); } }, [applied, page]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function action(id: string, kind: "confirm" | "cancel" | "reverse") { const reason = kind === "reverse" ? window.prompt("Why is this import being reversed?") : undefined; if (kind === "reverse" && !reason?.trim()) return; const promptText = kind === "confirm" ? "Confirming this import will add stock to inventory. Continue?" : kind === "cancel" ? "Cancel this draft import?" : "Reverse this import and remove its unused stock?"; if (!window.confirm(promptText)) return; const response = await fetch(`/api/imports/${id}${kind === "cancel" ? "" : `/${kind}`}`, { method: kind === "cancel" ? "DELETE" : "POST", headers: { "Content-Type": "application/json" }, body: kind === "reverse" ? JSON.stringify({ reason }) : undefined }); const result = await response.json(); if (!response.ok || !result.success) { setMessage(result.message || "Action failed."); return; } await load(); }
  const cards = [["Confirmed import cost", formatCurrencyLkr(summary?.totalShipmentCostLkr ?? 0)], ["Total KG imported", formatNumber(summary?.totalKg ?? 0)], ["Total bags imported", formatNumber(summary?.totalBags ?? 0)], ["Expected revenue", formatCurrencyLkr(summary?.totalExpectedRevenueLkr ?? 0)], ["Expected profit", formatCurrencyLkr(summary?.totalExpectedProfitLkr ?? 0)], ["Average margin", formatPercentage(summary?.expectedProfitMarginPercentage ?? 0)]];
  return <main className="p-4 text-neutral-900 md:p-6"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold">Imports</h1><p className="mt-1 text-sm text-neutral-500">Track shipments, landed cost, expected profit, and stock batches.</p></div><Link href="/import/new" className="rounded-xl bg-[#FFBF01] px-5 py-2.5 text-center text-sm font-bold text-black shadow-sm">New Import</Link></div>
    {message && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</div>}<div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label, value]) => <div key={label} className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase text-neutral-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>)}</div>
    <form onSubmit={(event) => { event.preventDefault(); setPage(1); setApplied(filters); }} className="mb-6 grid gap-3 rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm md:grid-cols-6"><input value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} placeholder="Search import, reference…" className="rounded-xl border p-2.5 md:col-span-2"/><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })} className="rounded-xl border p-2.5"><option>ALL</option><option>DRAFT</option><option>CONFIRMED</option><option>CANCELLED</option><option>REVERSED</option></select><input type="date" value={filters.dateFrom} onChange={(e) => setFilters({ ...filters, dateFrom: e.target.value })} className="rounded-xl border p-2.5"/><input type="date" value={filters.dateTo} onChange={(e) => setFilters({ ...filters, dateTo: e.target.value })} className="rounded-xl border p-2.5"/><input value={filters.supplierName} onChange={(e) => setFilters({ ...filters, supplierName: e.target.value })} placeholder="Supplier" className="rounded-xl border p-2.5"/><div className="flex gap-2 md:col-span-6"><button className="rounded-xl bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">Apply</button><button type="button" onClick={() => { const clear = { q: "", status: "ALL", dateFrom: "", dateTo: "", supplierName: "" }; setFilters(clear); setApplied(clear); setPage(1); }} className="rounded-xl border px-4 py-2 text-sm">Clear</button></div></form>
    <section className="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-neutral-50 text-neutral-600"><tr>{["Import No", "Date", "Supplier", "Products", "Total KG", "Bags", "Shipment Cost", "Expected Profit", "Margin", "Status", "Actions"].map((h) => <th key={h} className="p-4 font-semibold">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={11} className="p-8 text-center text-neutral-500">Loading imports…</td></tr> : rows.length === 0 ? <tr><td colSpan={11} className="p-8 text-center text-neutral-500">No imports found.</td></tr> : rows.map((row) => <tr key={row.id} className="border-t hover:bg-neutral-50"><td className="p-4 font-semibold"><Link href={`/import/${row.id}`} className="hover:underline">{row.importNo}</Link></td><td className="p-4">{formatDate(row.importDate)}</td><td className="p-4">{row.supplierName || "—"}</td><td className="p-4">{row.itemCount}</td><td className="p-4">{formatNumber(Number(row.totalKg))}</td><td className="p-4">{formatNumber(Number(row.totalBags))}</td><td className="p-4">{formatCurrencyLkr(Number(row.totalShipmentCostLkr))}</td><td className="p-4">{formatCurrencyLkr(Number(row.totalExpectedProfitLkr))}</td><td className="p-4">{formatPercentage(Number(row.expectedProfitMarginPercentage))}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge[row.status]}`}>{row.status}</span></td><td className="p-4"><div className="flex gap-2"><Link href={`/import/${row.id}`} className="font-semibold text-amber-700">View</Link>{row.status === "DRAFT" && <><Link href={`/import/${row.id}/edit`} className="font-semibold">Edit</Link><button onClick={() => void action(row.id, "confirm")} className="font-semibold text-emerald-700">Confirm</button><button onClick={() => void action(row.id, "cancel")} className="font-semibold text-red-700">Cancel</button></>}{row.status === "CONFIRMED" && <button onClick={() => void action(row.id, "reverse")} className="font-semibold text-orange-700">Reverse</button>}</div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t p-4"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><span className="text-sm text-neutral-500">Page {page} of {Math.max(meta.totalPages, 1)} · {meta.totalCount} imports</span><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></section>
  </main>;
}
