"use client";

import { useCallback, useEffect, useState } from "react";
import { formatCurrencyLkr, formatDate, formatNumber } from "@/lib/formatters";

type Product = { id: string; productName: string; sku: string | null; stockKg: number; stockBags: number; availableKg: number; availableBags: number; committedKg: number; availableBatchCount: number; averageCostPerKg: number; stockValue: number; defaultSellingPricePerKg: number; expectedProfitIfSold: number; hasLegacyStock: boolean };
type Batch = { id: string; batchNo: string; importDate: string; initialKg: number; remainingKg: number; remainingBags: number; costPerKgLkr: number; costPerBagLkr: number; stockValue: number; status: string; product: { id: string; productName: string }; importShipment: { id: string; importNo: string } };

export default function StocksPage() {
  const [products, setProducts] = useState<Product[]>([]); const [batches, setBatches] = useState<Batch[]>([]); const [q, setQ] = useState(""); const [batchQ, setBatchQ] = useState(""); const [productId, setProductId] = useState(""); const [status, setStatus] = useState("ALL"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setMessage(""); try { const params = new URLSearchParams({ limit: "100" }); if (q.trim()) params.set("q", q.trim()); if (batchQ.trim()) params.set("batchQ", batchQ.trim()); if (productId) params.set("productId", productId); if (status !== "ALL") params.set("batchStatus", status); const response = await fetch(`/api/stocks?${params}`); const result = await response.json(); if (!response.ok) throw new Error(result.message); setProducts(result.data); setBatches(result.batches); } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to load stocks."); } finally { setLoading(false); } }, [q, batchQ, productId, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  return <main className="space-y-6 p-4 text-neutral-900 md:p-6"><div><h1 className="text-3xl font-semibold">Stocks</h1><p className="mt-1 text-sm text-neutral-500">Read-only product inventory and batch-level landed cost.</p></div>{message && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</div>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><label className="block max-w-xl"><span className="mb-1 block text-xs font-semibold uppercase text-neutral-500">Search products</span><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Product name or SKU" className="w-full rounded-xl border px-3 py-2.5"/></label></section>
    <Table title="Product inventory" heads={["Product", "SKU", "On hand KG", "On hand bags", "Committed KG", "Available batches", "Average cost / KG", "Stock value", "Selling price / KG", "Expected profit"]}>{loading && !products.length ? <Empty columns={10} text="Loading inventory…"/> : products.length ? products.map((product) => <tr key={product.id} className="border-t"><td className="p-4 font-semibold">{product.productName}{product.hasLegacyStock && <span className="mt-1 block max-w-xs text-xs font-medium text-orange-700">Legacy stock has no batch cost history. Run the legacy batch script before selling it.</span>}</td><td className="p-4">{product.sku || "—"}</td><td className="p-4">{formatNumber(product.stockKg)}</td><td className="p-4">{formatNumber(product.stockBags)}</td><td className="p-4">{formatNumber(product.committedKg)}</td><td className="p-4">{product.availableBatchCount}</td><td className="p-4">{formatCurrencyLkr(product.averageCostPerKg)}</td><td className="p-4">{formatCurrencyLkr(product.stockValue)}</td><td className="p-4">{formatCurrencyLkr(product.defaultSellingPricePerKg)}</td><td className="p-4">{formatCurrencyLkr(product.expectedProfitIfSold)}</td></tr>) : <Empty columns={10} text="No products found."/>}</Table>
    <section className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-3"><label><span className="mb-1 block text-xs font-semibold uppercase text-neutral-500">Batch / import</span><input value={batchQ} onChange={(e) => setBatchQ(e.target.value)} placeholder="Batch or import no" className="w-full rounded-xl border px-3 py-2.5"/></label><label><span className="mb-1 block text-xs font-semibold uppercase text-neutral-500">Product</span><select value={productId} onChange={(e) => setProductId(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"><option value="">All products</option>{products.map((p) => <option key={p.id} value={p.id}>{p.productName}</option>)}</select></label><label><span className="mb-1 block text-xs font-semibold uppercase text-neutral-500">Batch status</span><select value={status} onChange={(e) => setStatus(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"><option>ALL</option><option>ACTIVE</option><option>DEPLETED</option><option>REVERSED</option></select></label></section>
    <Table title="Batch inventory" heads={["Batch no", "Product", "Import no", "Import date", "Initial KG", "Remaining KG", "Remaining bags", "Cost / KG", "Cost / bag", "Stock value", "Status"]}>{loading && !batches.length ? <Empty columns={11} text="Loading batches…"/> : batches.length ? batches.map((batch) => <tr key={batch.id} className="border-t"><td className="p-4 font-semibold">{batch.batchNo}</td><td className="p-4">{batch.product.productName}</td><td className="p-4">{batch.importShipment.importNo}</td><td className="p-4">{formatDate(batch.importDate)}</td><td className="p-4">{formatNumber(batch.initialKg)}</td><td className="p-4">{formatNumber(batch.remainingKg)}</td><td className="p-4">{formatNumber(batch.remainingBags)}</td><td className="p-4">{formatCurrencyLkr(batch.costPerKgLkr)}</td><td className="p-4">{formatCurrencyLkr(batch.costPerBagLkr)}</td><td className="p-4">{formatCurrencyLkr(batch.stockValue)}</td><td className="p-4"><span className="rounded-full bg-neutral-100 px-2 py-1 text-xs font-bold">{batch.status}</span></td></tr>) : <Empty columns={11} text="No batches found."/>}</Table>
  </main>;
}
function Table({ title, heads, children }: { title: string; heads: string[]; children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><h2 className="border-b p-5 text-lg font-semibold">{title}</h2><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-neutral-50"><tr>{heads.map((head) => <th key={head} className="p-4 font-semibold">{head}</th>)}</tr></thead><tbody>{children}</tbody></table></div></section>; }
function Empty({ columns, text }: { columns: number; text: string }) { return <tr><td colSpan={columns} className="p-8 text-center text-neutral-500">{text}</td></tr>; }
