"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { calculateImportItem, calculateImportShipmentTotals } from "@/lib/imports/import-calculations";
import { formatCurrencyLkr, formatCurrencyUsd, formatNumber, formatPercentage } from "@/lib/formatters";

type Product = { id: string; productName: string; sku: string | null; kgPerBag: number; defaultSellingPricePerKg: number };
type Item = { productId: string; quantityKg: string; kgPerBag: string; usdAmountPerKg: string; exchangeRateLkrUsd: string; undiyalPaidLkr: string; dutyTaxLkr: string; clearingChargesLkr: string; miscellaneousLkr: string; sellingPricePerKgLkr: string };
const emptyItem = (): Item => ({ productId: "", quantityKg: "", kgPerBag: "", usdAmountPerKg: "0", exchangeRateLkrUsd: "0", undiyalPaidLkr: "0", dutyTaxLkr: "0", clearingChargesLkr: "0", miscellaneousLkr: "0", sellingPricePerKgLkr: "0" });
const inputClass = "w-full rounded-xl border border-neutral-300 px-3 py-2 text-sm outline-none focus:border-amber-500";

export function ImportForm({ importId }: { importId?: string }) {
  const router = useRouter(); const [products, setProducts] = useState<Product[]>([]);
  const [header, setHeader] = useState({ importDate: new Date().toISOString().slice(0, 10), supplierName: "", referenceNo: "", containerNo: "", notes: "" });
  const [items, setItems] = useState<Item[]>([emptyItem()]); const [loading, setLoading] = useState(Boolean(importId)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void (async () => { try { const productResponse = await fetch("/api/products?limit=100"); const productResult = await productResponse.json(); if (!productResponse.ok) throw new Error(productResult.message || "Failed to load products."); setProducts(productResult.data); if (importId) { const response = await fetch(`/api/imports/${importId}`); const result = await response.json(); if (!response.ok) throw new Error(result.message); const data = result.data; if (data.status !== "DRAFT") throw new Error("Only draft imports can be edited."); setHeader({ importDate: String(data.importDate).slice(0, 10), supplierName: data.supplierName ?? "", referenceNo: data.referenceNo ?? "", containerNo: data.containerNo ?? "", notes: data.notes ?? "" }); setItems(data.items.map((item: Record<string, unknown>) => ({ productId: String(item.productId), quantityKg: String(item.quantityKg), kgPerBag: String(item.kgPerBag), usdAmountPerKg: String(item.usdAmountPerKg), exchangeRateLkrUsd: String(item.exchangeRateLkrUsd), undiyalPaidLkr: String(item.undiyalPaidLkr), dutyTaxLkr: String(item.dutyTaxLkr), clearingChargesLkr: String(item.clearingChargesLkr), miscellaneousLkr: String(item.miscellaneousLkr), sellingPricePerKgLkr: String(item.sellingPricePerKgLkr) }))); } } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to load form."); } finally { setLoading(false); } })(); }, [importId]);
  const calculated = useMemo(() => items.map((item) => { try { return calculateImportItem({ quantityKg: Number(item.quantityKg), kgPerBag: Number(item.kgPerBag), usdAmountPerKg: Number(item.usdAmountPerKg), exchangeRateLkrUsd: Number(item.exchangeRateLkrUsd), undiyalPaidLkr: Number(item.undiyalPaidLkr), dutyTaxLkr: Number(item.dutyTaxLkr), clearingChargesLkr: Number(item.clearingChargesLkr), miscellaneousLkr: Number(item.miscellaneousLkr), sellingPricePerKgLkr: Number(item.sellingPricePerKgLkr) }); } catch { return null; } }), [items]);
  const totals = calculateImportShipmentTotals(calculated.filter((value) => value !== null));
  function update(index: number, key: keyof Item, value: string) { setItems((current) => current.map((item, i) => i === index ? { ...item, [key]: value } : item)); }
  function selectProduct(index: number, productId: string) { const product = products.find((p) => p.id === productId); setItems((current) => current.map((item, i) => i === index ? { ...item, productId, kgPerBag: product ? String(product.kgPerBag) : item.kgPerBag, sellingPricePerKgLkr: product ? String(product.defaultSellingPricePerKg) : item.sellingPricePerKgLkr } : item)); }
  async function save(view: boolean) { setSaving(true); setMessage(""); try { const response = await fetch(importId ? `/api/imports/${importId}` : "/api/imports", { method: importId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...header, items: items.map((item) => ({ ...item, quantityKg: Number(item.quantityKg), kgPerBag: Number(item.kgPerBag), usdAmountPerKg: Number(item.usdAmountPerKg), exchangeRateLkrUsd: Number(item.exchangeRateLkrUsd), undiyalPaidLkr: Number(item.undiyalPaidLkr), dutyTaxLkr: Number(item.dutyTaxLkr), clearingChargesLkr: Number(item.clearingChargesLkr), miscellaneousLkr: Number(item.miscellaneousLkr), sellingPricePerKgLkr: Number(item.sellingPricePerKgLkr) })) }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Failed to save import."); router.push(view || importId ? `/import/${result.data.id}` : "/import"); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to save import."); } finally { setSaving(false); } }
  if (loading) return <div className="p-6 text-neutral-500">Loading import…</div>;
  return <form onSubmit={(event: FormEvent) => { event.preventDefault(); void save(true); }} className="space-y-6">{message && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</div>}
    <section className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-2 xl:grid-cols-4"><Field label="Import date"><input required type="date" value={header.importDate} onChange={(e) => setHeader({ ...header, importDate: e.target.value })} className={inputClass}/></Field><Field label="Supplier name"><input value={header.supplierName} onChange={(e) => setHeader({ ...header, supplierName: e.target.value })} className={inputClass}/></Field><Field label="Reference no"><input value={header.referenceNo} onChange={(e) => setHeader({ ...header, referenceNo: e.target.value })} className={inputClass}/></Field><Field label="Container no"><input value={header.containerNo} onChange={(e) => setHeader({ ...header, containerNo: e.target.value })} className={inputClass}/></Field><label className="md:col-span-2 xl:col-span-4"><span className="mb-1 block text-xs font-semibold uppercase text-neutral-500">Notes</span><textarea value={header.notes} onChange={(e) => setHeader({ ...header, notes: e.target.value })} className={inputClass}/></label></section>
    <section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Import items</h2><button type="button" onClick={() => setItems([...items, emptyItem()])} className="rounded-xl border px-4 py-2 text-sm font-semibold">Add product</button></div>{items.map((item, index) => { const calc = calculated[index]; const labels: Record<Exclude<keyof Item, "productId">, string> = { quantityKg: "Quantity KG", kgPerBag: "KG per bag", usdAmountPerKg: "USD / KG", exchangeRateLkrUsd: "Exchange rate", undiyalPaidLkr: "Undiyal LKR", dutyTaxLkr: "Duty / tax LKR", clearingChargesLkr: "Clearing LKR", miscellaneousLkr: "Miscellaneous LKR", sellingPricePerKgLkr: "Selling price / KG" }; return <div key={index} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h3 className="font-semibold">Item {index + 1}</h3>{items.length > 1 && <button type="button" onClick={() => setItems(items.filter((_, i) => i !== index))} className="text-sm font-semibold text-red-700">Remove</button>}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Field label="Product"><select required value={item.productId} onChange={(e) => selectProduct(index, e.target.value)} className={inputClass}><option value="">Select product</option>{products.map((p) => <option key={p.id} value={p.id}>{p.productName}{p.sku ? ` · ${p.sku}` : ""}</option>)}</select></Field>{(Object.keys(labels) as (keyof typeof labels)[]).map((key) => <Field key={key} label={labels[key]}><input required step="any" min="0" type="number" value={item[key]} onChange={(e) => update(index, key, e.target.value)} className={inputClass}/></Field>)}</div><div className="mt-4 grid gap-3 rounded-xl bg-neutral-50 p-4 sm:grid-cols-2 xl:grid-cols-4">{[["Bags", formatNumber(calc?.quantityBags ?? 0)], ["Amount paid", formatCurrencyUsd(calc?.amountPaidUsd ?? 0)], ["USD converted", formatCurrencyLkr(calc?.usdConvertedLkr ?? 0)], ["Final cost", formatCurrencyLkr(calc?.finalItemCostLkr ?? 0)], ["Cost / KG", formatCurrencyLkr(calc?.costPerKgLkr ?? 0)], ["Cost / bag", formatCurrencyLkr(calc?.costPerBagLkr ?? 0)], ["Expected revenue", formatCurrencyLkr(calc?.expectedRevenueLkr ?? 0)], ["Profit / margin", `${formatCurrencyLkr(calc?.expectedProfitLkr ?? 0)} · ${formatPercentage(calc?.expectedProfitMarginPercentage ?? 0)}`]].map(([label, value]) => <div key={label}><p className="text-xs text-neutral-500">{label}</p><p className="font-semibold">{value}</p></div>)}</div></div>; })}</section>
    <section className="grid gap-3 rounded-2xl border bg-neutral-900 p-5 text-white sm:grid-cols-2 xl:grid-cols-7">{[["Total KG", formatNumber(totals.totalKg)], ["Total bags", formatNumber(totals.totalBags)], ["Total USD", formatCurrencyUsd(totals.totalAmountPaidUsd)], ["Shipment cost", formatCurrencyLkr(totals.totalShipmentCostLkr)], ["Revenue", formatCurrencyLkr(totals.totalExpectedRevenueLkr)], ["Profit", formatCurrencyLkr(totals.totalExpectedProfitLkr)], ["Margin", formatPercentage(totals.expectedProfitMarginPercentage)]].map(([label, value]) => <div key={label}><p className="text-xs text-neutral-400">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</section>
    <div className="flex flex-wrap justify-end gap-3"><button type="button" onClick={() => void save(false)} disabled={saving} className="rounded-xl border px-5 py-2.5 font-semibold disabled:opacity-50">Save Draft</button><button disabled={saving} className="rounded-xl bg-[#FFBF01] px-5 py-2.5 font-bold text-black disabled:opacity-50">{saving ? "Saving…" : "Save Draft and View"}</button></div></form>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1 block text-xs font-semibold uppercase text-neutral-500">{label}</span>{children}</label>; }
