import "dotenv/config";

import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }),
});

async function main() {
  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured.");
  if (process.env.CONFIRM_LEGACY_BATCH_BACKFILL !== "true") {
    throw new Error("Set CONFIRM_LEGACY_BATCH_BACKFILL=true to create legacy batches.");
  }

  const products = await prisma.product.findMany({
    where: { stockKg: { gt: 0 }, stockBatches: { none: {} } },
  });
  console.log(`Found ${products.length} products with unbatched legacy stock.`);

  for (const product of products) {
    await prisma.$transaction(async (tx) => {
      const skuPart = (product.sku || product.id.slice(0, 8))
        .replace(/[^a-zA-Z0-9-]/g, "-")
        .toUpperCase();
      const importNo = `LEGACY-${skuPart}`;
      const existing = await tx.importShipment.findUnique({ where: { importNo } });
      if (existing) return;

      const shipment = await tx.importShipment.create({
        data: {
          importNo,
          importDate: product.createdAt,
          supplierName: "Legacy opening stock",
          notes: "Generated by the one-time legacy stock batch backfill. Cost history was unavailable.",
          status: "CONFIRMED",
          totalKg: product.stockKg,
          totalBags: product.stockBags,
          confirmedAt: new Date(),
          items: {
            create: {
              productId: product.id,
              quantityKg: product.stockKg,
              quantityBags: product.stockBags,
              kgPerBag: product.kgPerBag,
              sellingPricePerKgLkr: product.defaultSellingPricePerKg,
              expectedRevenueLkr:
                Number(product.stockKg) * Number(product.defaultSellingPricePerKg),
              expectedProfitLkr:
                Number(product.stockKg) * Number(product.defaultSellingPricePerKg),
              expectedProfitMarginPercentage:
                Number(product.defaultSellingPricePerKg) > 0 ? 100 : 0,
            },
          },
        },
        include: { items: true },
      });
      const item = shipment.items[0];
      const availableKg = Math.max(
        0,
        Number(product.stockKg) -
          Number(product.committedKg) -
          Number(product.unavailableKg)
      );
      const availableBags = Math.max(
        0,
        Number(product.stockBags) -
          Number(product.committedBags) -
          Number(product.unavailableBags)
      );
      const batch = await tx.stockBatch.create({
        data: {
          productId: product.id,
          importShipmentId: shipment.id,
          importItemId: item.id,
          batchNo: importNo,
          importDate: product.createdAt,
          initialKg: product.stockKg,
          initialBags: product.stockBags,
          remainingKg: availableKg,
          remainingBags: availableBags,
          kgPerBag: product.kgPerBag,
          costPerKgLkr: 0,
          costPerBagLkr: 0,
          status: availableKg > 0 ? "ACTIVE" : "DEPLETED",
        },
      });

      // Existing, not-yet-dispatched orders already contribute to committed
      // product stock. Link those commitments to the legacy batch so deleting
      // one later restores the same batch instead of losing batch availability.
      const committedItems = await tx.orderItem.findMany({
        where: {
          productId: product.id,
          order: {
            deletedAt: null,
            orderStatus: { notIn: ["DELETED", "CANCELLED"] },
            deliveryStatus: "NOT_DISPATCHED",
          },
          batchAllocations: { none: {} },
        },
      });
      for (const orderItem of committedItems) {
        await tx.orderItemBatchAllocation.create({
          data: {
            orderId: orderItem.orderId,
            orderItemId: orderItem.id,
            productId: product.id,
            stockBatchId: batch.id,
            quantityKg: orderItem.quantityKg,
            quantityBags: orderItem.quantityBags,
            costPerKgLkr: 0,
            totalCostLkr: 0,
          },
        });
      }
    });
  }
  console.log("Legacy batch backfill complete. Legacy batch cost is zero by design.");
}

main()
  .catch((error) => { console.error(error); process.exitCode = 1; })
  .finally(async () => prisma.$disconnect());
